### ISSUE TITLE
As a new user, I want to register for an account on the platform so that I can access personalized features and services.

### ISSUE THREAD

**Issue by kaemoney0147** [kaemoney0147/Arnaty#1]
Acceptance Criteria:

1) The registration page should be accessible from the homepage via a "Sign Up" button/link.
The registration form should include the following fields:
First Name (required)
Last Name (required)
Email Address (required, must be unique)
Password (required, must meet complexity requirements)
Confirm Password (required, must match the Password field)
The registration form should have validation to ensure that all required fields are completed correctly:
Display an error message if any required field is missing.
Display an error message if the email address is already in use.
Display an error message if the password does not meet complexity requirements (e.g., minimum 8 characters, including at least one uppercase letter, one lowercase letter, one number, and one special character).
Display an error message if the passwords do not match.

**Comment by kaemoney0147** [comment]
Mr Ferdinard pls kindly visit this and review before the developer start working on it

**Comment by Feddy-T** [comment]
Am working on it
